In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.2'

In [3]:
# pip install --upgrade openpyxl

In [4]:
emp = pd.read_excel(r'C:\Users\DELL\AVSCODE\8.EDA\Rawdata.xlsx')

In [5]:
emp

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [6]:
id(emp)

2396630978432

In [7]:
emp.columns

Index(['Name', 'Domain', 'Age', 'Location', 'Salary', 'Exp'], dtype='object')

In [8]:
emp.shape

(6, 6)

In [9]:
emp.head()

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year

In [10]:
emp.tail()

     Name          Domain     Age   Location   Salary      Exp
1  Teddy^         Testing  45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#     NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics     NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics   67-yr        NaN   30000-  5+ year
5     Kim             NLP    55yr      Delhi  6000^$0      10+

In [11]:
emp

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [12]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       4 non-null      object
 3   Location  4 non-null      object
 4   Salary    6 non-null      object
 5   Exp       5 non-null      object
dtypes: object(6)
memory usage: 420.0+ bytes

In [13]:
emp.isnull()

    Name  Domain    Age  Location  Salary    Exp
0  False   False  False     False   False  False
1  False   False  False     False   False  False
2  False   False   True      True   False  False
3  False   False   True     False   False   True
4  False   False  False      True   False  False
5  False   False  False     False   False  False

In [14]:
emp.isna()

    Name  Domain    Age  Location  Salary    Exp
0  False   False  False     False   False  False
1  False   False  False     False   False  False
2  False   False   True      True   False  False
3  False   False   True     False   False   True
4  False   False  False      True   False  False
5  False   False  False     False   False  False

In [15]:
emp.isnull().sum()

Name        0
Domain      0
Age         2
Location    2
Salary      0
Exp         1
dtype: int64

In [16]:
emp.dtypes

Name        object
Domain      object
Age         object
Location    object
Salary      object
Exp         object
dtype: object

# Data Cleaning

In [17]:
emp

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [18]:
emp['Name']

0      Mike
1    Teddy^
2     Uma#r
3      Jane
4    Uttam*
5       Kim
Name: Name, dtype: object

In [19]:
emp['Name'] = emp['Name'].str.replace(r'\W','',regex = True) # non word char

In [20]:
emp['Name']

0     Mike
1    Teddy
2     Umar
3     Jane
4    Uttam
5      Kim
Name: Name, dtype: object

In [21]:
emp

    Name          Domain       Age   Location   Salary      Exp
0   Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy         Testing    45' yr  Bangalore  10%%000       <3
2   Umar  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3   Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam      Statistics     67-yr        NaN   30000-  5+ year
5    Kim             NLP      55yr      Delhi  6000^$0      10+

In [22]:
emp.columns

Index(['Name', 'Domain', 'Age', 'Location', 'Salary', 'Exp'], dtype='object')

In [23]:
emp['Domain']

0     Datascience#$
1           Testing
2    Dataanalyst^^#
3       Ana^^lytics
4        Statistics
5               NLP
Name: Domain, dtype: object

In [24]:
emp['Domain'] =emp['Domain'].str.replace(r'\W','',regex='True')

In [25]:
emp['Domain']

0    Datascience
1        Testing
2    Dataanalyst
3      Analytics
4     Statistics
5            NLP
Name: Domain, dtype: object

In [26]:
emp['Age']

0    34 years
1      45' yr
2         NaN
3         NaN
4       67-yr
5        55yr
Name: Age, dtype: object

In [27]:
emp['Age'] = emp['Age'].str.extract('(\\d+)')

In [28]:
emp['Age']

0     34
1     45
2    NaN
3    NaN
4     67
5     55
Name: Age, dtype: object

In [29]:
emp['Age'] = emp['Age'].fillna(emp['Age'].median())

TypeError: Cannot convert ['34' '45' nan nan '67' '55'] to numeric

In [34]:
emp["Age"]

0     34
1     45
2    NaN
3    NaN
4     67
5     55
Name: Age, dtype: object

In [35]:
emp

    Name       Domain  Age   Location   Salary      Exp
0   Mike  Datascience   34     Mumbai   5^00#0       2+
1  Teddy      Testing   45  Bangalore  10%%000       <3
2   Umar  Dataanalyst  NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics  NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics   67        NaN   30000-  5+ year
5    Kim          NLP   55      Delhi  6000^$0      10+

In [36]:
emp['Salary'] = emp['Salary'].fillna(emp['Salary'].median())

TypeError: Cannot convert ['5^00#0' '10%%000' '1$5%000' '2000^0' '30000-' '6000^$0'] to numeric

In [37]:
emp

    Name       Domain  Age   Location   Salary      Exp
0   Mike  Datascience   34     Mumbai   5^00#0       2+
1  Teddy      Testing   45  Bangalore  10%%000       <3
2   Umar  Dataanalyst  NaN        NaN  1$5%000   4> yrs
3   Jane    Analytics  NaN   Hyderbad   2000^0      NaN
4  Uttam   Statistics   67        NaN   30000-  5+ year
5    Kim          NLP   55      Delhi  6000^$0      10+

In [40]:
emp['Salary'] =emp['Salary'].str.replace(r'\W','',regex='True')

In [39]:
emp

    Name       Domain  Age   Location Salary      Exp
0   Mike  Datascience   34     Mumbai   5000       2+
1  Teddy      Testing   45  Bangalore  10000       <3
2   Umar  Dataanalyst  NaN        NaN  15000   4> yrs
3   Jane    Analytics  NaN   Hyderbad  20000      NaN
4  Uttam   Statistics   67        NaN  30000  5+ year
5    Kim          NLP   55      Delhi  60000      10+

In [41]:
emp['Exp'] = emp['Exp'].str.extract('(\\d+)')

In [42]:
emp

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst  NaN        NaN  15000    4
3   Jane    Analytics  NaN   Hyderbad  20000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [43]:
emp['Age'] = emp['Age'].fillna(emp['Age'].median())

TypeError: Cannot convert ['34' '45' nan nan '67' '55'] to numeric

In [30]:
emp.dtype()

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [31]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       4 non-null      object
 3   Location  4 non-null      object
 4   Salary    6 non-null      object
 5   Exp       5 non-null      object
dtypes: object(6)
memory usage: 420.0+ bytes

In [47]:
emp['Name'] = emp['Name'].astype('string')
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      string
 1   Domain    6 non-null      object
 2   Age       4 non-null      object
 3   Location  4 non-null      object
 4   Salary    6 non-null      object
 5   Exp       5 non-null      object
dtypes: object(5), string(1)
memory usage: 420.0+ bytes

In [51]:
emp['Domain'] = emp['Domain'].astype('string')
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      string
 1   Domain    6 non-null      string
 2   Age       4 non-null      object
 3   Location  4 non-null      string
 4   Salary    6 non-null      object
 5   Exp       5 non-null      object
dtypes: object(3), string(3)
memory usage: 420.0+ bytes

In [52]:
emp['Location'] = emp['Location'].astype('string')
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      string
 1   Domain    6 non-null      string
 2   Age       4 non-null      object
 3   Location  4 non-null      string
 4   Salary    6 non-null      object
 5   Exp       5 non-null      object
dtypes: object(3), string(3)
memory usage: 420.0+ bytes

In [54]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      string
 1   Domain    6 non-null      string
 2   Age       4 non-null      object
 3   Location  4 non-null      string
 4   Salary    6 non-null      object
 5   Exp       5 non-null      object
dtypes: object(3), string(3)
memory usage: 420.0+ bytes

In [56]:

emp["Age"] = emp["Age"].astype("Int64")

In [57]:
emp

    Name       Domain   Age   Location Salary  Exp
0   Mike  Datascience    34     Mumbai   5000    2
1  Teddy      Testing    45  Bangalore  10000    3
2   Umar  Dataanalyst  <NA>       <NA>  15000    4
3   Jane    Analytics  <NA>   Hyderbad  20000  NaN
4  Uttam   Statistics    67       <NA>  30000    5
5    Kim          NLP    55      Delhi  60000   10

In [58]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      string
 1   Domain    6 non-null      string
 2   Age       4 non-null      Int64
 3   Location  4 non-null      string
 4   Salary    6 non-null      object
 5   Exp       5 non-null      object
dtypes: Int64(1), object(2), string(3)
memory usage: 426.0+ bytes

In [59]:
emp["Age"] = emp["Age"].fillna(emp["Age"].median()).astype("int64")
emp

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst   50       <NA>  15000    4
3   Jane    Analytics   50   Hyderbad  20000  NaN
4  Uttam   Statistics   67       <NA>  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [63]:
emp["Location"] = emp["Location"].fillna(emp["Location"].mode())
emp

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst   50   Hyderbad  15000    4
3   Jane    Analytics   50   Hyderbad  20000  NaN
4  Uttam   Statistics   67       <NA>  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [66]:
emp["Location"] = emp["Location"].fillna(emp["Location"].mode()[0])
emp

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst   50   Hyderbad  15000    4
3   Jane    Analytics   50   Hyderbad  20000  NaN
4  Uttam   Statistics   67   Hyderbad  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [67]:
print(emp["Location"])
print(emp["Location"].isnull().sum())

0       Mumbai
1    Bangalore
2     Hyderbad
3     Hyderbad
4     Hyderbad
5        Delhi
Name: Location, dtype: string
0

In [68]:
emp['Exp'] = emp['Exp'].fillna(emp['Exp'].median())

TypeError: Cannot convert ['2' '3' '4' nan '5' '10'] to numeric

In [70]:

emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      string
 1   Domain    6 non-null      string
 2   Age       6 non-null      int64
 3   Location  6 non-null      string
 4   Salary    6 non-null      object
 5   Exp       5 non-null      object
dtypes: int64(1), object(2), string(3)
memory usage: 420.0+ bytes

In [74]:
emp['Exp'] = emp['Exp'].astype('Int64')
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      string
 1   Domain    6 non-null      string
 2   Age       6 non-null      int64
 3   Location  6 non-null      string
 4   Salary    6 non-null      object
 5   Exp       5 non-null      Int64
dtypes: Int64(1), int64(1), object(1), string(3)
memory usage: 426.0+ bytes

In [75]:
emp["Exp"] = emp["Exp"].fillna(emp["Exp"].median()).astype("Int64")

In [76]:
emp

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst   50   Hyderbad  15000    4
3   Jane    Analytics   50   Hyderbad  20000    4
4  Uttam   Statistics   67   Hyderbad  30000    5
5    Kim          NLP   55      Delhi  60000   10